### ISSUE TITLE
Switch build/publish to be uv based

### ISSUE THREAD

**Issue by vonsteer** [vonsteer/taskiq-aio-sqs#17]
Maybe it will be easier to use something like that for publishing:

```yml
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv version ${{  github.ref_name }}"
      - run: uv build
      - run: uv publish --trusted-publishing always
```

For this you just need to specify "publisher" in your pypi settings for this package and pass `UV_PUBLISH_TOKEN` to environment variables in settings of this repository. More information about it can be found here: 
- [uv docs about publishing](https://docs.astral.sh/uv/guides/package/#building-and-publishing-a-package)
- [example repository](https://github.com/astral-sh/trusted-publishing-examples)

After that you can get rid of `build-system`, `tool.setuptools-git-versioning` and `dynamic = ["version"]`settings in `pyproject.toml`

_Originally posted by @danfimov in https://github.com/vonsteer/taskiq-aio-sqs/pull/16#discussion_r2068729494_
